server.port=8081

spring.datasource.url=jdbc:postgresql://postgresql:5432/${DB_NAME}
spring.datasource.username=gennaro-syskoplan
spring.datasource.password=Test1234
spring.jpa.hibernate.ddl-auto=update